### ISSUE TITLE
How to obtain a copy of nemosys_tpls.tar.gz

### ISSUE THREAD

**Issue by Wangduu** [IllinoisRocstar/Nemosys#3]
Hello, 
I am trying to build Nemosys , but how to obtain a copy of _nemosys_tpls.tar.gz_ ?

**Comment by msafdari1234** [comment]
We do not recommend using this anymore. All TPLs are available as standalone open source projects and they are mostly easy to install. We recommend you obtain and compile them from source, or install them directly on your system. If you still like to try tpl collection we prepared, please reach out to me following directions given in [how to obtain promesh](https://www.illinoisrocstar.com/products/promesh) webpage.

**Comment by Wangduu** [comment]
Ok , I'll obtain them from source , thanks.
